### ISSUE TITLE
Dependency Missing

### ISSUE THREAD

**Issue by truongle2211** [amzn/ion-test-driver#2]
I have installed all the dependency as in requirements.txt. However, when I run `ion_test_driver.py`, I have the following error:
<img width="1079" alt="screen shot 2018-09-06 at 8 31 28 pm" src="https://user-images.githubusercontent.com/15175817/45191975-e4f22f80-b213-11e8-93a0-9e907e131cf6.png">

I couldn't find the module `amazon.iontest`. Can anyone help me to resolve this error ? Thanks

**Comment by tgregg** [comment]
@truongle2211 I'm looking in to this. I think there's something wrong with the package structure. `amazon.iontest` is the package declared by the ion-test-driver, so it should always be available.

**Comment by tgregg** [comment]
@truongle2211 Please pull the latest revision of the package and try to install/run using the following steps:
`pip3 install -r requirements.txt`
`pip3 install .`
`python3 amazon/iontest/ion_test_driver.py --help`

Reopen this issue if you still experience problems.

Thanks!
